### ISSUE TITLE
Cards with Infest retain the infest counter during Match and Keep

### ISSUE THREAD

**Issue by Ragaxus** [erasels/PackmasterCharacter#381]
During Match and Keep, the event where you play memory to add cards to your deck, if cards with Infest are in the tableau, the infest icon is visible even while the cards are face down:

![image](https://user-images.githubusercontent.com/10427478/215243495-f41a7979-8a98-4a51-ba71-f0f9d9e730f1.png)

(I feel certain there's a funny joke to be made about an insect-themed mechanic causing a software issue...but for the life of me I can't think of what that would be......)

**Comment by erasels** [comment]
This is not so much a bug with this mod but with stslib. I'll open an issue there
