### ISSUE TITLE
Reservoir does not perform its stated effect consistently

### ISSUE THREAD

**Issue by zxcvbnm39934** [erasels/PackmasterCharacter#387]
## ISSUE

Playing "Reservoir" from the "Go With The Flow" pack does not perform the effect stated on the card text ("Draw cards equal to the number of cards discarded this way") if you choose to discard your entire hand. Furthermore, ending your turn afterwards will result in enemies not performing any actions.

## TO REPLICATE

1) Play Reservoir, then choose all cards in your hand to be discarded.
2) No cards will be drawn, and any enemies in the current combat will not perform any actions.

## MODLIST
 - basemod (5.50.0)
 - actlikeit (1.2.7)
 - stslib (2.7.1)
 - coloredmap (2.4.1)
 - coloredpowertips (2.3.0)
 - OptimizeTheSpire (1.1.0)
 - quickrestart (2.0.5)
 - superfastmode (1.0.8)
 - anniv5 (1.1.5)

**Comment by lobbienjonsji** [comment]
Your version for packmaster is outdated, the workshop version got temporarily reverted because of a gamebreaking bug when the hand is empty. The bug will fixed with the next release.

**Comment by zxcvbnm39934** [comment]
Ok, that's great!
