### ISSUE TITLE
Stylepoints show current hat's pack.

### ISSUE THREAD

**Issue by Mwallx** [erasels/PackmasterCharacter#461]

**Comment by erasels** [comment]
what does this mean?

**Comment by Alchyr** [comment]
they mean oddities Style Points, which gets a random card from pack of current hat to show what pack it is

**Comment by Mwallx** [comment]
actually could do it myself, but didnt find how the hat name string was loaded..

**Comment by Mwallx** [comment]
cool , I was thinking adding the pack name in card text, didnt realize could use the preview card.
