### ISSUE TITLE
Amplify not proccing. 

### ISSUE THREAD

**Issue by vicentemar97** [erasels/PackmasterCharacter#544]
If I'm understanding it correctly, the Amplify mechanic from Marisa should trigger if you have enough unspent energy for it automatically. 

I can't get it to trigger even if I have just the right amount of energy. 

I think it is bugged. Awesome mod, thank you!

**Comment by erasels** [comment]
Exactly, the card should have a white border glow (instead of the typical blue) if it would amplify.

So if you play Masterspark at 2 Energy, it should consume both for the increased damage. Does it only not consume energy but still do the effect or does it just never do anything but the base effect? 

Which card specifically did you try it on? And what is your modlist, maybe there's an incompatibility

**Comment by vicentemar97** [comment]
Oh yeah sorry, should have clarified. Nothing happens, neither the energy gets consumed or the effect procs. The card DOES glow.

Exhaustive doesn't seem to ever exhaust cards either... 

These are the mods I use. 

Mod list:
 - basemod (5.51.1)
 - stslib (2.9.0)
 - anniv5 (1.6.1)
 - coloredmap (2.4.1)
 - coloredpowertips (2.3.0)
 - Curses_Come_First (1.0)
 - HighlightPath (0.0.3)
 - mintyspire (2.5.5)
 - quickrestart (2.0.5)
 - OptimizeTheSpire (1.1.0)
 - permNeow (1)
 - superfastmode (1.0.8)
 - UnlockEverythingMod (5.0.0)
 
 I wanted to to do some digging about the mod compabitilty potential issue. 
 
 I deactivated all the mods and started enabling them one by one, with a custom run to try the mechanic. 
 It is working now all of the sudden, even though I have the same mods as I did before... I don't understand it. Maybe I'm missing something. I'm gonna play normal runs to see if I manage to replicate it. If I find something worth sharing I will update you. I guess we can close this for now. Sorry I couldn't replicate it. 

Thanks!

**Comment by vicentemar97** [comment]
Got lucky and draw Marisa. Can confirm it is working right, which is strange, but good too!

**Comment by erasels** [comment]
Huh, that is incredibly weird. Glad to hear it's working for you now, thanks for keeping me up to date. If it stops working again feel free to repoen this
