### ISSUE TITLE
Finisher not showing up in the All for One pack

### ISSUE THREAD

**Issue by strangebit** [erasels/PackmasterCharacter#703]
![AllForOneFinisher](https://github.com/erasels/PackmasterCharacter/assets/11712728/91871c9b-8292-45f7-9c09-6484b26a0c9a)

According to the [9 April changelog](https://steamcommunity.com/sharedfiles/filedetails/changelog/2920075378) it should be there?

**Comment by erasels** [comment]
Thanks for pointing that out, we didn't notice that Finisher was already in the Silent pack. In the next update, we'll replace Finisher in the Silent pack with Leg Sweep.
